#!/bin/sh
#
# This script runs pre-commit and is responsible 
# for running the gitPreCommit library automatically
# to prevent merge conflicts
#
#
echo "Beginning gitPreCommit"
echo "$(pwd)"
start "$(pwd)\libs\gitPreCommit.exe"
echo "gitPreCommit ran successfully"
git add .
