#!/bin/sh
#
# This script runs pre-commit and is responsible 
# for running the gitPreCommit library automatically
# to prevent merge conflicts
#
#
start "$(pwd)\libs\gitPreCommit.exe"
echo "gitPreCommit ran successfully, starting tsr rebuild"
start "$(pwd)\libs\utilscripts\RunCreateObjectRepo.bat"
echo "TSR Rebuild Complete"
git add .